apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: test-app-updater
  namespace: argocd
spec:
  applicationRefs:
  - namePattern: "test-app"
    images:
    - alias: myapp
      imageName: us-central1-docker.pkg.dev/applied-ridge-414907/my-docker-repo/hello-test-app
      commonUpdateSettings:
        updateStrategy: newest-build
        pullSecret: "pullsecret:argocd/gcr-secret"
  writeBackConfig:
    method: argocd