apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-container
        image: us-central1-docker.pkg.dev/applied-ridge-414907/my-docker-repo/hello-test-app:v1.0
        ports:
        - containerPort: 80