# helm/my-app/values.yaml

replicaCount: 2

image:
  repository: myapp=us-central1-docker.pkg.dev/applied-ridge-414907/my-docker-repo/hello-test-app
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi